//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_table
    {
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
        public string Company_Address { get; set; }
        public string Company_Phone { get; set; }
    }
}
