//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_table
    {
        public int Login_Id { get; set; }
        public int Reg_Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Login_Type { get; set; }
    }
}
