//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jobportalEntities : DbContext
    {
        public jobportalEntities()
            : base("name=jobportalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application_table> application_table { get; set; }
        public virtual DbSet<company_table> company_table { get; set; }
        public virtual DbSet<job_table> job_table { get; set; }
        public virtual DbSet<login_table> login_table { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_countRegid(string eml, string pwd)
        {
            var emlParameter = eml != null ?
                new ObjectParameter("eml", eml) :
                new ObjectParameter("eml", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_countRegid", emlParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_countRegidMailCheck(string eml)
        {
            var emlParameter = eml != null ?
                new ObjectParameter("eml", eml) :
                new ObjectParameter("eml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_countRegidMailCheck", emlParameter);
        }
    
        public virtual int sp_insertCompanyTable(Nullable<int> cid, string cna, string des, string addr, string phn)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var desParameter = des != null ?
                new ObjectParameter("des", des) :
                new ObjectParameter("des", typeof(string));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phnParameter = phn != null ?
                new ObjectParameter("phn", phn) :
                new ObjectParameter("phn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertCompanyTable", cidParameter, cnaParameter, desParameter, addrParameter, phnParameter);
        }
    
        public virtual int sp_insertLoginTable(Nullable<int> rid, string eml, string pwd, string ltype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var emlParameter = eml != null ?
                new ObjectParameter("eml", eml) :
                new ObjectParameter("eml", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var ltypeParameter = ltype != null ?
                new ObjectParameter("ltype", ltype) :
                new ObjectParameter("ltype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertLoginTable", ridParameter, emlParameter, pwdParameter, ltypeParameter);
        }
    
        public virtual int sp_insertUserTable(Nullable<int> uid, string una, Nullable<int> ag, string addr, string ph, string gdr, string qul, string skl, Nullable<int> exp, string sts)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var gdrParameter = gdr != null ?
                new ObjectParameter("gdr", gdr) :
                new ObjectParameter("gdr", typeof(string));
    
            var qulParameter = qul != null ?
                new ObjectParameter("qul", qul) :
                new ObjectParameter("qul", typeof(string));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertUserTable", uidParameter, unaParameter, agParameter, addrParameter, phParameter, gdrParameter, qulParameter, sklParameter, expParameter, stsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxRegid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxRegid");
        }
    
        public virtual ObjectResult<string> sp_selLoginType(string eml, string pwd)
        {
            var emlParameter = eml != null ?
                new ObjectParameter("eml", eml) :
                new ObjectParameter("eml", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_selLoginType", emlParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_selRegid(string eml, string pwd)
        {
            var emlParameter = eml != null ?
                new ObjectParameter("eml", eml) :
                new ObjectParameter("eml", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_selRegid", emlParameter, pwdParameter);
        }
    }
}
