//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public int User_Age { get; set; }
        public string User_Address { get; set; }
        public string User_Phone { get; set; }
        public string User_Gender { get; set; }
        public string User_Qualification { get; set; }
        public string User_Skills { get; set; }
        public int User_Experience { get; set; }
        public string User_Status { get; set; }
    }
}
